name: StrikeDeath
main: com.c45y.KillDB.KillDB
version: 0.3
database: true
permissions:
    KillDB.perms:
        description: Can check ratings
        default: true
commands:
    rating:
        description: Returns the rating of the player.
        permission: KillDB.perms
        usage: /rating [player]
    top5:
        description: Returns the top 5 players and their rating.
        permission: KillDB.perms
        usage: /top5
    ranking:
        description: Returns rank based on rating.
        permission: KillDB.perms
        usage: /rating [player]