name: StrikeDeath
main: com.c45y.KillDB.KillDB
version: 0.3
database: true
permissions:
    KillDB.perms:
        description: Can check ratings
        default: true
commands:
    rating:
        description: Returns the rating of the player.
        permission: KillDB.perms
        usage: /rating [player]